import { integer, jsonb, pgTable, serial, text, timestamp } from "drizzle-orm/pg-core";

/**
 * The 'ai_tickets' table will serve as the primary audit log for all AI-generated tickets.
 * This table captures a complete, immutable record of each request, including the
 * original user prompt, the structured AI output, and the final Shortcut story ID.
 * This is crucial for debugging, historical analysis, and ensuring data integrity.
 */
export const aiTickets = pgTable("ai_tickets", {
  // A unique, auto-incrementing integer ID to serve as the primary key.
  id: serial("id").primaryKey(),

  // The unique ID of the user who initiated the ticket creation.
  userId: integer("user_id").notNull(),

  // The raw text prompt provided by the user.
  rawPrompt: text("raw_prompt").notNull(),

  // The structured JSON payload generated by the Gemini API.
  // We use `jsonb` for efficient indexing and querying of the JSON data.
  geminiOutput: jsonb("gemini_output").notNull(),

  // The ID of the ticket that was successfully created in Shortcut.
  shortcutStoryId: integer("shortcut_story_id").notNull(),

  // Timestamp for when the record was created. Automatically defaults to the current time.
  createdAt: timestamp("created_at").defaultNow().notNull(),

  // Timestamp for the last time the record was updated.
  updatedAt: timestamp("updated_at").notNull(),
});

// For demonstration purposes, this is a simplified 'users' table.
// In a real-world application, this would be part of the full schema
// and would be used to enforce foreign key constraints.
export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
});